services:
  murin-run-php:
    build:
      context: .
    container_name: murin-run-php-service
    ports:
      - "8080:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    volumes:
      - .:/var/www/html
    depends_on:
      - postgresql
      - mongodb
    command: php -S 0.0.0.0:8000 router.php

  postgresql:
    image: postgres:15
    container_name: murin-run-php-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mongopostgre_db
    ports:
      - "5113:5432"
    volumes:
      - murin-run-php-postgresql:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: murin-run-php-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: mongomurim_db
    ports:
      - "27111:27017"
    volumes:
      - murin-run-php-mongodb:/data/db

volumes:
  murin-run-php-postgresql:
    driver: local
  murin-run-php-mongodb:
    driver: local
