services:
  murin-run-php:
    build:
      context: .
    container_name: murin-run-php-service
    ports:
      - "8080:8000"
    develop:
      watch:
        - path: .
          target: /var/www/html
          action: sync
        - path: ./composer.json
          action: rebuild
        - path: ./composer.lock
          action: rebuild
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: murin-run-php-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
      MONGO_INITDB_DATABASE: mongomurim_db
    ports:
      - "27111:27017"
    volumes:
      - murin-run-php-mongodb:/data/db/mongodb

  postgresql:
    image: postgres:15
    container_name: murin-run-php-postgresql
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mongopostgre_db
    ports:
      - "5112:5432"
    volumes:
      - murin-run-php-postgresql:/data/db/postgresql

volumes:
  murin-run-php-mongodb:
    driver: local
  murin-run-php-postgresql:
    driver: local
